version: 2
jobs:
  build:
    machine: 
      enabled: true
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: ssh $SSH_USER@$SSH_HOST -p 17536
